[2024-08-22 08:56:30,980][basic_search][INFO][color_logger.py:203] Logfile: /gyc_data/fray_data/project_hw/logs_gray_clapboard_search/basic_search_2024-08-22-08-56-30-979935.log
[2024-08-22 08:56:30,996][basic_search][INFO][generic_advisor.py:231] [BO auto selection]  acq_type: eic. acq_optimizer_type: random_scipy.
[2024-08-22 08:56:30,996][basic_search][WARNING][base.py:64] [Build Surrogate] Use probabilistic random forest based on scikit-learn. For better performance, please install pyrfr: https://open-box.readthedocs.io/en/latest/installation/install_pyrfr.html
[2024-08-22 08:56:31,003][basic_search][INFO][html_visualizer.py:462] Please open the html file to view visualization result: file:///gyc_data/fray_data/project_hw/logs_gray_clapboard_search/history/basic_search/basic_search_2024-08-22-08-56-31-002165.html
[2024-08-22 08:56:31,005][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.0,
  'x1': 0.0,
  'x2': 0.0,
  'x3': 0.0,
  'x4': 0.0,
  'x5': 0.0,
  'x6': 0.0,
  'x7': 0.0,
  'x8': 0.0,
  'x9': 0.0,
})

[2024-08-22 08:56:31,005][basic_search][INFO][generic_smbo.py:308] Iter 1, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,005][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,006][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.7279405926611294,
  'x1': 0.9499742972597989,
  'x2': 0.7526882657314036,
  'x3': 0.9095905616183217,
  'x4': 0.946379070313236,
  'x5': 0.4795634909343367,
  'x6': 0.5724671094916657,
  'x7': 0.444995715131276,
  'x8': 0.9400588172157769,
  'x9': 0.5800032868853725,
})

[2024-08-22 08:56:31,006][basic_search][INFO][generic_smbo.py:308] Iter 2, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,006][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,006][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.03614860193556757,
  'x1': 0.3439800282640001,
  'x2': 0.23932206206506823,
  'x3': 0.10008465053031357,
  'x4': 0.02126150129486082,
  'x5': 0.250558351076302,
  'x6': 0.7432900692946732,
  'x7': 0.9516301639325209,
  'x8': 0.8442261077436554,
  'x9': 0.6343351154505843,
})

[2024-08-22 08:56:31,006][basic_search][INFO][generic_smbo.py:308] Iter 3, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,006][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,006][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.8790956403644901,
  'x1': 0.9427607725639505,
  'x2': 0.5630341223763493,
  'x3': 0.36751960726423083,
  'x4': 0.27811817290598295,
  'x5': 0.9794426458467425,
  'x6': 0.000981989840045716,
  'x7': 0.4338659832720473,
  'x8': 0.04359746870400705,
  'x9': 0.12376203292358123,
})

[2024-08-22 08:56:31,007][basic_search][INFO][generic_smbo.py:308] Iter 4, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,007][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,007][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.9653728356564678,
  'x1': 0.01635095919745566,
  'x2': 0.06171659410057839,
  'x3': 0.9873799759044158,
  'x4': 0.7749934682651927,
  'x5': 0.388051768964929,
  'x6': 0.347299510026859,
  'x7': 0.17213842167141757,
  'x8': 0.24101293441667448,
  'x9': 0.1140460269465805,
})

[2024-08-22 08:56:31,007][basic_search][INFO][generic_smbo.py:308] Iter 5, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,007][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,007][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.026231294509629133,
  'x1': 0.45945679027146236,
  'x2': 0.7986159467012641,
  'x3': 0.9492979033984171,
  'x4': 0.006667848480388039,
  'x5': 0.44404795779277884,
  'x6': 0.7256647768637968,
  'x7': 0.1587225208446431,
  'x8': 0.4131068711313147,
  'x9': 0.2318736657482383,
})

[2024-08-22 08:56:31,007][basic_search][INFO][generic_smbo.py:308] Iter 6, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,008][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,008][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.30687825714245875,
  'x1': 0.9088587262146897,
  'x2': 0.6999224434372338,
  'x3': 0.008543436189430098,
  'x4': 0.7992893133197085,
  'x5': 0.23916656181539364,
  'x6': 0.7187524900768187,
  'x7': 0.3710212823717549,
  'x8': 0.03650859743744439,
  'x9': 0.658373496508449,
})

[2024-08-22 08:56:31,008][basic_search][INFO][generic_smbo.py:308] Iter 7, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,008][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,008][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.9959809480139837,
  'x1': 0.19645580069996194,
  'x2': 0.36485704861260926,
  'x3': 0.462459089359162,
  'x4': 0.8567583983251008,
  'x5': 0.9038876792489628,
  'x6': 0.7459431072468974,
  'x7': 0.8532894863201146,
  'x8': 0.9784797638151636,
  'x9': 0.020385944589098037,
})

[2024-08-22 08:56:31,008][basic_search][INFO][generic_smbo.py:308] Iter 8, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,008][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,009][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.03020388830391252,
  'x1': 0.3694649909785751,
  'x2': 0.9322979036462228,
  'x3': 0.0092052656882321,
  'x4': 0.20528384126932775,
  'x5': 0.8845392509259696,
  'x6': 0.22242425556229883,
  'x7': 0.26958862339654865,
  'x8': 0.7677630182121308,
  'x9': 0.7828412744765727,
})

[2024-08-22 08:56:31,009][basic_search][INFO][generic_smbo.py:308] Iter 9, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,009][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
[2024-08-22 08:56:31,009][basic_search][ERROR][generic_smbo.py:290] Exception in objective function:
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 81, in obj_func
    cost = self.black_box.get_cost_from_seq(seq)
  File "/gyc_data/fray_data/project_hw/bayes.py", line 36, in get_cost_from_seq
    output_param = OutputParam(len = self.io_len, sequence=(c_uint32 * self.io_len)(*action_seq))
TypeError: incompatible types, IOUint instance instead of c_uint instance

config: Configuration(values={
  'x0': 0.006597957848324287,
  'x1': 0.083146498362767,
  'x2': 0.8553973491024185,
  'x3': 0.8602051572135317,
  'x4': 0.8851180963667753,
  'x5': 0.14447259039752158,
  'x6': 0.32221912781217743,
  'x7': 0.3131141233622694,
  'x8': 0.7543973357061585,
  'x9': 0.989118747665533,
})

[2024-08-22 08:56:31,009][basic_search][INFO][generic_smbo.py:308] Iter 10, objectives: [inf]. constraints: None.
[2024-08-22 08:56:31,009][basic_search][ERROR][html_visualizer.py:141] Failed to save visualization data!
Traceback (most recent call last):
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 119, in save_visualization_data
    draw_data = self.generate_basic_data()
  File "/gyc_data/fray_data/py38hwvenv/lib/python3.8/site-packages/openbox/visualization/html_visualizer.py", line 162, in generate_basic_data
    constraints = [round(v, 6) for v in obs.constraints]
TypeError: 'NoneType' object is not iterable
